#include <rpiplc-version.h>

#define xstr(a) str(a)
#define str(a) #a



const int LIB_RPIPLC_VERSION_MAJOR_NUM = __LIB_RPIPLC_VERSION_MAJOR_NUM;
const int LIB_RPIPLC_VERSION_MINOR_NUM = __LIB_RPIPLC_VERSION_MINOR_NUM;
const int LIB_RPIPLC_VERSION_PATCH_NUM = __LIB_RPIPLC_VERSION_PATCH_NUM;

const char* LIB_RPIPLC_VERSION_MAJOR = xstr(__LIB_RPIPLC_VERSION_MAJOR_NUM);
const char* LIB_RPIPLC_VERSION_MINOR = xstr(__LIB_RPIPLC_VERSION_MINOR_NUM);
const char* LIB_RPIPLC_VERSION_PATCH = xstr(__LIB_RPIPLC_VERSION_PATCH_NUM);
const char* LIB_RPIPLC_VERSION = \
	xstr(__LIB_RPIPLC_VERSION_MAJOR_NUM) "." \
	xstr(__LIB_RPIPLC_VERSION_MINOR_NUM) "." \
	xstr(__LIB_RPIPLC_VERSION_PATCH_NUM);
