#include <rpiplc-version.h>

#define xstr(a) str(a)
#define str(a) #a


#define _LIB_RPIPLC_VERSION_MAJOR_NUM 3
#define _LIB_RPIPLC_VERSION_MINOR_NUM 0
#define _LIB_RPIPLC_VERSION_PATCH_NUM 0



const int LIB_RPIPLC_VERSION_MAJOR_NUM = _LIB_RPIPLC_VERSION_MAJOR_NUM;
const int LIB_RPIPLC_VERSION_MINOR_NUM = _LIB_RPIPLC_VERSION_MINOR_NUM;
const int LIB_RPIPLC_VERSION_PATCH_NUM = _LIB_RPIPLC_VERSION_PATCH_NUM;

const char* LIB_RPIPLC_VERSION_MAJOR = xstr(_LIB_RPIPLC_VERSION_MAJOR_NUM);
const char* LIB_RPIPLC_VERSION_MINOR = xstr(_LIB_RPIPLC_VERSION_MINOR_NUM);
const char* LIB_RPIPLC_VERSION_PATCH = xstr(_LIB_RPIPLC_VERSION_PATCH_NUM);
const char* LIB_RPIPLC_VERSION = \
	xstr(_LIB_RPIPLC_VERSION_MAJOR_NUM) "." \
	xstr(_LIB_RPIPLC_VERSION_MINOR_NUM) "." \
	xstr(_LIB_RPIPLC_VERSION_PATCH_NUM);
