#ifndef __RPIPLC_VERSION_H__
#define __RPIPLC_VERSION_H__

#define LIB_RPIPLC_VERSION_MAJOR "1"
#define LIB_RPIPLC_VERSION_MINOR "0"
#define LIB_RPIPLC_VERSION_PATCH "1"
#define LIB_RPIPLC_VERSION	LIB_RPIPLC_VERSION_MAJOR "." LIB_RPIPLC_VERSION_MINOR "." LIB_RPIPLC_VERSION_PATCH

#endif
